### PR TITLE
Adding Anne Durif in nonperm.yml

### PR DESCRIPTION
**Pull request by lesommer**
in response to #59

### CODE REVIEW

**Comment by auraoupa** [comment]
I am sorry, the script is on my shut down desk computer ... I will upload it to the repo when I'm coming back in 10 days ! It's a simple imagemagick script written by Jean-Michel (maybe he still has it too ?)

**Comment by lesommer** [comment]
@brankart : do you think you would be able to exhumate a version of this script ?

**Comment by auraoupa** [comment]
@lesommer I've put the mail picture for Anne at the right location in the main branch, you can now go on with this pull request 

Also the scripts used to generate are now available in makemailspic

**Comment by lesommer** [comment]
Thanks !

**Pull request merged**
